server:
  port: 8080

spring:
  application:
    name: dongmanee
  profiles:
    active: dev
  config:
    import:
      - application-oauth.yml
      - application-email.yml

logging:
  level:
    com.dongmanee: DEBUG